export const IPC_CHANNELS = {
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  libraryGetCached: 'library:getCached',
  librarySync: 'library:sync',
  wishlistGetCached: 'wishlist:getCached',
  wishlistAdd: 'wishlist:add',
  wishlistRemove: 'wishlist:remove',
  wishlistRefreshPrices: 'wishlist:refreshPrices',
  wishlistSyncFromSteam: 'wishlist:syncFromSteam',
  steamSearchGames: 'steam:searchGames',
  historyGetEvents: 'history:getEvents',
  sessionLogGetSessions: 'sessionLog:getSessions',
  sessionLogGetEntries: 'sessionLog:getEntries',
  sessionLogDeleteSession: 'sessionLog:deleteSession',
  dealsGetCached: 'deals:getCached',
  wishlistDealsGetCached: 'deals:getWishlistCached',
  pollingTriggerNow: 'polling:triggerNow',
  pollingGetStatus: 'polling:getStatus',
  notificationsTest: 'notifications:test',
  notifiedDealsClear: 'notifiedDeals:clear',
  metadataResolveMissing: 'metadata:resolveMissing',
  metadataGetAll: 'metadata:getAll',
  achievementsGet: 'achievements:get',
  secretsStatus: 'secrets:status',
  secretsSetSteamApiKey: 'secrets:setSteamApiKey',
  secretsSetGGDealsApiKey: 'secrets:setGGDealsApiKey',
  dealsFoundEvent: 'event:dealsFound'
} as const

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]
