export const IPC_CHANNELS = {
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  libraryGetCached: 'library:getCached',
  librarySync: 'library:sync',
  wishlistGetCached: 'wishlist:getCached',
  wishlistRemove: 'wishlist:remove',
  wishlistSyncFromSteam: 'wishlist:syncFromSteam',
  historyGetEvents: 'history:getEvents',
  historyRemoveEvents: 'history:removeEvents',
  sessionLogGetSessions: 'sessionLog:getSessions',
  sessionLogGetEntries: 'sessionLog:getEntries',
  sessionLogDeleteSession: 'sessionLog:deleteSession',
  dealsGetCached: 'deals:getCached',
  wishlistDealsGetCached: 'deals:getWishlistCached',
  pollingTriggerNow: 'polling:triggerNow',
  pollingGetStatus: 'polling:getStatus',
  notificationsTest: 'notifications:test',
  notifiedDealsClear: 'notifiedDeals:clear',
  notificationsDismissAll: 'notifications:dismissAll',
  metadataResolveMissing: 'metadata:resolveMissing',
  metadataResolveCancel: 'metadata:resolveCancel',
  metadataResolveStatus: 'metadata:resolveStatus',
  metadataResolveOne: 'metadata:resolveOne',
  metadataResolveOneProgress: 'metadata:resolveOneProgress',
  metadataGetAll: 'metadata:getAll',
  metadataRefreshAll: 'metadata:refreshAll',
  queuesGetGGDeals: 'queues:getGGDeals',
  queuesGetGGDealsQuota: 'queues:getGGDealsQuota',
  priceHistoryGetForAppId: 'priceHistory:getForAppId',
  queuesGetSteamMetadata: 'queues:getSteamMetadata',
  timersGetAll: 'timers:getAll',
  localMediaOpenGameFolder: 'localMedia:openGameFolder',
  achievementsGet: 'achievements:get',
  secretsStatus: 'secrets:status',
  secretsSetSteamApiKey: 'secrets:setSteamApiKey',
  secretsSetGGDealsApiKey: 'secrets:setGGDealsApiKey',
  dealsFoundEvent: 'event:dealsFound',
  dealsBatchFoundEvent: 'event:dealsBatchFound'
} as const

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]
